### ISSUE TITLE
Quietly absorb 503 errors from API

### ISSUE THREAD

**Issue by StafDehat** [StafDehat/scripts#15]
In cloud-image-transfer.sh, see if we can detect random 503 errors from the API and recover gracefully instead of bailing.  As-is, current behaviour is the following:
<pre>
2015-01-14 03:43:32 Waiting for completion - will check every 60 seconds.

Error: Unable to query task details - maybe API is unavailable?
       Maybe your API token just expired?
Script will attempt to retry.
Response data from API was as follows:

Response code: 503
</pre>

Docs say this means the API was "unavailable":
http://docs.rackspace.com/images/api/v2/ci-devguide/content/GET_getTask_tasks__taskID__Image_Task_Calls.html#GET_getTask_tasks__taskID__Image_Task_Calls-Request

**Comment by jduhls** [comment]
Any luck with this? I can't seem to get past 503's either.

**Comment by StafDehat** [comment]
Just haven't gotten to it.  It seems the API sometimes returns a 503 for perfectly valid calls - must be something going wrong in the backend.  To the end user (ie: my script), it just means try the exact same call a second time, so there's really no reason I couldn't just detect the 503s and retry, just like I do with md5 mismatch errors in the download/upload calls.

I didn't realize this was actually impacting anyone, though - thought it was just a personal perfectionist to-do item.  I'll see if I can make it a priority for you.  That being said, October's one hell of a month for me, so this may not happen for a bit.

When you see this, is the script chugging along fine as expected, then suddenly one step fails with the above 503 error for seemingly no reason?  If you retry, does it fail at exactly the same spot, or somewhere different?  If you could copy/paste the full execution and output of the script for me (or as much as you're comfortable sharing - strip your API key for sure), that'd be helpful.  Email it to me?
andrew at rootmypc dot net

**Comment by jduhls** [comment]
No problem. No - I get different numbers of "Waiting for completion..." lines each time I run it. I hacked your script to interpret "503" as STATUS="pending" for the moment. That allowed the script to progress. However, at a new roadblock "413" (Over Limit: The number of items returned is above the allowed limit.):
```bash
Initiating import task in xxx.
Successully initiated an image import task in region 'xxx'.
Task ID: xxx-xxx-xxx-xxx

Monitoring status of image import.
2015-10-15 11:16:33 Waiting for completion - will check every 60 seconds.
2015-10-15 11:17:34 Waiting for completion - will check every 60 seconds.
2015-10-15 11:18:36 Waiting for completion - will check every 60 seconds.
2015-10-15 11:19:36 Waiting for completion - will check every 60 seconds.
2015-10-15 11:20:37 Waiting for completion - will check every 60 seconds.
2015-10-15 11:21:42 Waiting for completion - will check every 60 seconds.
2015-10-15 11:22:42 Waiting for completion - will check every 60 seconds.
2015-10-15 11:23:43 Waiting for completion - will check every 60 seconds.
Error: Import task complete, but status does not indicate success.
Status: failure
Message: Image cannot be imported. Error code: '413'
```

...I'll keep hacking.

**Comment by StafDehat** [comment]
Actually, no amount of hacking my script is going to get you around that 413.  Here's the key to those error codes:
396 - invalid VHD (non-VHD file or VHD file that doesn't contain all the correct headers)
413 - invalid Size (virtual size > 40GB)
609 - invalid Size (physical size > 40GB)
721 - invalid chain depth (has one or more parents)
523 - invalid disk type (only Fixed and Dynamic types allowed as of now)
111 - any other error

So 413 means the Virtual Size of the image is >40G, so the image can't be imported.  That's odd though, because the min_disk value on the image should reflect the virtual size of the VHD, and my script should have detected that min_disk was >40G.  Did you run an API call to change the min_disk value on the image before running the script?  If so, you only solved part of the problem.  This section of the script has more info:
https://github.com/StafDehat/scripts/blob/master/cloud-image-transfer.sh#L317-L333

So the *why* is buried in implementation details, but if you're running into size problems then this is your best option:
1) If you're working with a source *server*, take an image of it.  If you're working from a source *image*, skip this step.
2) Build a >=2G NextGen Standard server from your image.
3) Login to your new server and delete content as necessary to reduce total used disk space <40G.
4) Run this: "cat /dev/zero > /zero; rm -f /zero"   (yes this step seems insane, but it's very important)
5) Resize the server down to a 1G NextGen Standard instance.
6) After the resize, confirm the system is online and healthy, then take a new image.

That new image is the one you'll want to use with my script.

**Comment by allenwipe** [comment]
@jduhls I am running into the 503 api error as well, mind sharing the code for setting status to pending?

**Comment by StafDehat** [comment]
God, I'm sorry guys.  This took way longer than it should have.  As a sysadmin, I hate code maintainers like myself.

Anyway, the fix is committed:
https://github.com/StafDehat/scripts/commit/ff4f42f2c4985e826b562c1d6514cf2ec9d43ce3
